export const Git = [
  {
    key: "g",
    name: "Git...",
    type: "bindings",
    bindings: [
      {
        key: "/",
        name: "Search Commits",
        command: "gitlens.showCommitSearch",
        type: "command",
        when: "gitlens:enabled && config.gitlens.keymap == 'alternate'",
      },
      {
        key: "a",
        name: "Stage",
        type: "command",
        command: "git.stage",
      },
      {
        key: "b",
        name: "Checkout",
        type: "command",
        command: "git.checkout",
      },
      {
        key: "B",
        name: "Browse",
        type: "command",
        command: "gitlens.openFileInRemote",
      },
      {
        key: "c",
        name: "Commit",
        type: "command",
        command: "git.commit",
      },
      {
        key: "C",
        name: "Cherry Pick",
        type: "command",
        command: "gitlens.views.cherryPick",
      },
      {
        key: "d",
        name: "Delete Branch",
        type: "command",
        command: "git.deleteBranch",
      },
      {
        key: "f",
        name: "Fetch",
        type: "command",
        command: "git.fetch",
      },
      {
        key: "F",
        name: "Pull From",
        type: "command",
        command: "git.pullFrom",
      },
      {
        key: "g",
        name: "Graph",
        type: "command",
        command: "git-graph.view",
      },
      {
        key: "h",
        name: "Heatmap",
        type: "command",
        command: "gitlens.toggleFileHeatmap",
      },
      {
        key: "H",
        name: "History",
        type: "command",
        command: "git.viewFileHistory",
      },
      {
        key: "i",
        name: "Init",
        type: "command",
        command: "git.init",
      },
      {
        key: "j",
        name: "Next Change",
        type: "command",
        command: "workbench.action.editor.nextChange",
      },
      {
        key: "k",
        name: "Previous Change",
        type: "command",
        command: "workbench.action.editor.previousChange",
      },
      {
        key: "l",
        name: "Toggle Line Blame",
        type: "command",
        command: "gitlens.toggleLineBlame",
        when: "editorTextFocus && gitlens:canToggleCodeLens && gitlens:enabled && config.gitlens.keymap == 'alternate'",
      },
      {
        key: "L",
        name: "Toggle GitLens",
        type: "command",
        command: "gitlens.toggleCodeLens",
        when: "editorTextFocus && gitlens:canToggleCodeLens && gitlens:enabled && config.gitlens.keymap == 'alternate'",
      },
      {
        key: "m",
        name: "Merge",
        type: "command",
        command: "git.merge",
      },
      {
        key: "p",
        name: "Push",
        type: "command",
        command: "git.push",
      },
      {
        key: "P",
        name: "Pull",
        type: "command",
        command: "git.pull",
      },
      {
        key: "s",
        name: "Stash",
        type: "command",
        command: "workbench.view.scm",
      },
      {
        key: "S",
        name: "Status",
        type: "command",
        command: "gitlens.showQuickRepoStatus",
        when: "gitlens:enabled && config.gitlens.keymap == 'alternate'",
      },
      {
        key: "t",
        name: "Create Tag",
        type: "command",
        command: "git.createTag",
      },
      {
        key: "T",
        name: "Delete Tag",
        type: "command",
        command: "git.deleteTag",
      },
      {
        key: "U",
        name: "Unstage",
        type: "command",
        command: "git.unstage",
      },
    ],
  },
];
